dist: xenial
sudo: false
language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - node_modules

addons:
  firefox: 66.0
  chrome: stable
  hosts:
    - lh # 'localhost' alias for SauceLabs Android

# limit the Travis 'build on push' feature to the master branch only
branches:
  only:
   - master
   - /^[1-9]\.x$/

script:
  - yarn install:dependencies
  - yarn build
  - yarn lint
  - if [[ $TRAVIS_PULL_REQUEST == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      wct
        --env saucelabs
        --webserver-hostname lh
      ;
    else
      xvfb-run -s '-screen 0 1024x768x24' yarn test;
    fi
  - yarn size-control
